export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";