import Head from 'next/head'
import Text from '../components/base/Text'
import InputField from '../components/base/InputField'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SecondHand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-screen place-items-center">
        <Text>Text sample</Text>
        <InputField
          type="text"
          value=""
          placeholder="login"
          label="Login"
          name="login"
          onChange=""
        />
      </div>
    </div>
  )
}
